import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/component/Navigation";
import localfont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });
// const rubic = IBM_Plex_Sans({ subsets: ["latin"], weight: ["400"] });

const mounment = localfont({
  src: "../../public/fonts/PPMonumentExtended-Regular.otf",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mounment.className}>
        <main>
          <Navigation />
          {children}
        </main>
      </body>
    </html>
  );
}
